# Use an official Node runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock) into the working directory
COPY package*.json ./

# Install your application's dependencies
RUN npm install

# Copy the rest of your application's code
COPY . .

# Build your Strapi application (if necessary)
RUN npm run build

# Expose the port Strapi runs on
EXPOSE 1337

# Run the app using CMD which defines your runtime execution
CMD ["npm", "run", "develop"]
